import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.TEST_URL || 'http://127.0.0.1:5186';
const output = process.env.TEST_OUTPUT || '/tmp/shanyi-browser-check';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.getByRole('checkbox').first().check();
  await page.getByRole('button', { name: '不建名档体验' }).click();
  await page.screenshot({ path: `${output}/home-desktop.png`, fullPage: true });
  await page.getByRole('button', { name: /01 八字排盘/ }).click();
  await page.getByRole('button', { name: '生成八字排盘分析' }).click();
  await page.getByRole('heading', { name: '专业细盘', exact: true }).waitFor();
  const chart = page.locator('.professional-chart-section');
  await chart.getByRole('button', { name: /切换到.*年开始的.*大运/ }).nth(2).click();
  const annualButtons = chart.getByRole('button', { name: /切换到\d+流年/ });
  const before = await chart.locator('.professional-title-actions').innerText();
  await annualButtons.nth(1).click();
  assert.notEqual(await chart.locator('.professional-title-actions').innerText(), before);
  assert.equal(await chart.locator('[aria-label="流月横向列表"] button').count(), 12);
  await chart.locator('[aria-label="流月横向列表"] button').nth(2).click();
  const dayCount = await chart.locator('[aria-label="流日横向列表"] button').count();
  assert.ok(dayCount >= 29 && dayCount <= 33, `full solar-term month: ${dayCount}`);
  await page.screenshot({ path: `${output}/report-desktop.png`, fullPage: true });
  await page.getByRole('button', { name: '命理学堂', exact: true }).first().click();
  await page.getByRole('tab', { name: '古籍研读', exact: true }).click();
  await page.locator('.classic-book-card').filter({ has: page.getByRole('heading', { name: '滴天髓', exact: true }) }).getByRole('button').click();
  await page.locator('.chapter-blocks section').first().waitFor();
  assert.match(page.url(), /learn\/classics\/ditiansui\/01/);
  await page.getByRole('button', { name: '下一篇', exact: true }).click();
  await page.waitForURL('**/02*');
  await page.goBack();
  await page.locator('.classic-chapter h1').filter({ hasText: '通天' }).waitFor();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('.chapter-blocks section').first().waitFor();
  await page.screenshot({ path: `${output}/classics-desktop.png`, fullPage: true });
  await page.getByRole('button', { name: '下载全书', exact: true }).click();
  await page.getByText('全书已可离线阅读', { exact: true }).waitFor({ timeout: 60000 });
  await page.context().setOffline(true);
  await page.getByRole('button', { name: '下一篇', exact: true }).click();
  await page.locator('.classic-chapter h1').filter({ hasText: '天干' }).waitFor();
  await page.locator('.chapter-blocks section').first().waitFor();
  await page.context().setOffline(false);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${output}/classics-mobile.png`, fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'mobile page overflow');
  await page.getByRole('tab', { name: '课程体系', exact: true }).click();
  await page.getByRole('tab', { name: '术语词典', exact: true }).click();
  await page.getByRole('tab', { name: '案例研习', exact: true }).click();
  await page.screenshot({ path: `${output}/learning-mobile.png`, fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'mobile tabs overflow');
  console.log('Guest report, classic routing/back/refresh, offline chapters, mobile navigation passed');
  const accountPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  accountPage.on('pageerror', error => errors.push(error.message));
  await accountPage.goto(base, { waitUntil: 'domcontentloaded' });
  await accountPage.getByRole('button', { name: '注册', exact: true }).click();
  await accountPage.locator('[name=username]').fill('browser_test');
  await accountPage.locator('[name=displayName]').fill('浏览器测试');
  await accountPage.locator('[name=password]').fill('test-only-password-123');
  await accountPage.locator('[name=confirmPassword]').fill('test-only-password-123');
  await accountPage.getByRole('checkbox').first().check();
  await accountPage.getByRole('button', { name: '注册并进入', exact: true }).click();
  await accountPage.getByRole('button', { name: /01 八字排盘/ }).click();
  await accountPage.getByRole('button', { name: '生成八字排盘分析' }).click();
  await accountPage.waitForURL(/#\/reports\/[^/]+$/);
  const reportUrl = accountPage.url();
  const oldStamp = await accountPage.locator('.report-revisions').innerText();
  await accountPage.getByRole('button', { name: '按最新规则重算', exact: true }).click();
  await accountPage.getByText('历史报告', { exact: false }).first().waitFor();
  const history = accountPage.locator('.report-revisions select');
  assert.equal(await history.locator('option').count(), 2);
  await history.selectOption({ index: 0 });
  assert.ok((await accountPage.locator('.report-revisions').innerText()).includes(oldStamp.split('\n')[0]));
  await accountPage.reload({ waitUntil: 'domcontentloaded' });
  await accountPage.locator('[name=username]').fill('browser_test');
  await accountPage.locator('[name=password]').fill('test-only-password-123');
  await accountPage.getByRole('button', { name: '登录并解锁' }).click();
  await accountPage.waitForURL(reportUrl);
  await accountPage.locator('.report-revisions select').waitFor();
  assert.equal(await accountPage.locator('.report-revisions select option').count(), 2);
  console.log('Local registration, encrypted archive snapshots and authenticated refresh passed');
  await accountPage.getByRole('button', { name: '功能首页', exact: true }).click();
  await accountPage.getByRole('button', { name: /01 八字排盘/ }).click();
  await accountPage.getByRole('checkbox', { name: '出生时辰未知' }).check();
  await accountPage.getByRole('button', { name: '生成八字排盘分析' }).click();
  await accountPage.getByRole('heading', { name: '时辰待补全' }).waitFor();
  assert.equal(await accountPage.getByRole('heading', { name: '专业细盘', exact: true }).count(), 0);
  assert.doesNotMatch(await accountPage.locator('body').innerText(), /undefined|NaN/);
  await accountPage.screenshot({ path: `${output}/unknown-hour.png`, fullPage: true });
  console.log('Unknown-hour boundary and year/month/day interactions passed');
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
